@startuml

skinparam linetype polyline

!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml 
!includeurl AzurePuml/Compute/AzureFunction.puml

'AzureFunction(rouletteFunctionS, "Eric Lippert's blog roulette", "HTTP Trigger")
'AzureFunction(crawlerFunctionS, "Eric Lippert's blog articles crawler", "HTTP Trigger")
'AzureBlobStorage(visitedArticlesS, "Visited articles", "as function binding")

actor user
participant "<$AzureFunction>" as rouletteFunction << roulette >>
participant "<$AzureFunction>" as crawlerFunction << crawler >>
participant "<$AzureBlobStorage>" as visitedArticles
note over crawlerFunction
  already implemented
  function
end note

user -> rouletteFunction: http request
activate rouletteFunction

rouletteFunction -> crawlerFunction: http request
crawlerFunction --> rouletteFunction: list of articles
rouletteFunction -> visitedArticles
visitedArticles --> rouletteFunction: list of visited articles
rouletteFunction -> rouletteFunction: filter acrticles and select one random
rouletteFunction -> visitedArticles: append article
visitedArticles -> rouletteFunction
rouletteFunction --> user: redirection link to the selected article
deactivate rouletteFunction

@enduml
