<pre class='metadata'>
Title: VIM in .NET - tecktalk proposal
Shortname: vimindotnet
Level: 1
Date: 2020-07-12
Status: DREAM
URL: https://ungerfall.github.io/bikeshed/techtalk-proposal-vim-in-dotnet

Editor: Leonid Petrov, EPAM Systems http://www.epam.com/, ungerfall@gmail.com

Abstract: Документ содержит предложение проверки технический доклад на тему vim в .net 

</pre>

Introduction {#intro}
=====================
